### ISSUE TITLE
Commit script is broken by commitlint upgrade

### ISSUE THREAD

**Issue by jrolfs** [hoverinc/hover-javascript#381]
😞

```
Users/jamie/Developer/Hover/web-react/node_modules/commitizen/dist/commitizen/adapter.js:1400
    throw new Error(`Could not find prompter method in the provided adapter module: ${adapterPath}`);
    ^

Error: Could not find prompter method in the provided adapter module: @commitlint/prompt
    at getPrompter (/Users/jamie/Developer/Hover/web-react/node_modules/commitizen/dist/commitizen/adapter.js:1400:11)
    at gitCz (/Users/jamie/Developer/Hover/web-react/node_modules/commitizen/dist/cli/strategies/git-cz.js:63:18)
    at bootstrap (/Users/jamie/Developer/Hover/web-react/node_modules/commitizen/dist/cli/git-cz.js:25:27)
    at Object.<anonymous> (/Users/jamie/Developer/Hover/web-react/node_modules/@hover/javascript/dist/scripts/commit.js:19:1)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by jrolfs** [comment]
@EvaFro
